import os
from pathlib import Path
from dotenv import load_dotenv

# Always load .env from the backend directory, regardless of where manage.py is run from
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=BASE_DIR / '.env')
SECRET_KEY = os.getenv('SECRET_KEY', 'dev-secret-key-change-in-production')
DEBUG = os.getenv('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ],
    },
}]

WSGI_APPLICATION = 'config.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

CORS_ALLOW_ALL_ORIGINS = True

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Addis_Ababa'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Path to knowledge base JSON
KNOWLEDGE_BASE_PATH = BASE_DIR.parent / 'data' / 'knowledge_base.json'

# ── Phase 3: SMS / Africa's Talking ──────────────────────────────────────────
AT_USERNAME   = os.getenv('AT_USERNAME', 'sandbox')
AT_API_KEY    = os.getenv('AT_API_KEY', '')
AT_SENDER_ID  = os.getenv('AT_SENDER_ID', 'HealthBot')
AT_SHORTCODE  = os.getenv('AT_SHORTCODE', '')   # incoming SMS shortcode
SMS_ENABLED   = os.getenv('SMS_ENABLED', 'False') == 'True'

# ── Phase 3: Reminder scheduler (APScheduler) ────────────────────────────────
SCHEDULER_ENABLED = os.getenv('SCHEDULER_ENABLED', 'True') == 'True'

# ── Phase 4: DHIS2 Integration ────────────────────────────────────────────────
DHIS2_URL         = os.getenv('DHIS2_URL', '')
DHIS2_USERNAME    = os.getenv('DHIS2_USERNAME', '')
DHIS2_PASSWORD    = os.getenv('DHIS2_PASSWORD', '')
DHIS2_ORG_UNIT    = os.getenv('DHIS2_ORG_UNIT', 'ImspTQPwCqd')
DHIS2_DATASET_UID = os.getenv('DHIS2_DATASET_UID', 'pBOMPrpg1QX')

# ── Google Places API ─────────────────────────────────────────────────────────
GOOGLE_PLACES_API_KEY = os.getenv('GOOGLE_PLACES_API_KEY', '')

# ── Google Cloud Translation API ──────────────────────────────────────────────
# Get key at: https://console.cloud.google.com → APIs → Cloud Translation API
# Free tier: 500,000 characters/month
GOOGLE_TRANSLATE_API_KEY = os.getenv('GOOGLE_TRANSLATE_API_KEY', '')

# Path to pre-built translations JSON (generated by scripts/generate_translations.py)
TRANSLATIONS_JSON_PATH = BASE_DIR / 'data' / 'translations.json'

# Auto-load static translations into cache on startup
TRANSLATION_PRELOAD = os.getenv('TRANSLATION_PRELOAD', 'True') == 'True'
