import json, os
PATH = os.path.join(os.path.dirname(__file__), '..', 'data', 'knowledge_base.json')
d = json.load(open(PATH, encoding='utf-8'))

FACILITIES = [
  # ── Addis Ababa ──────────────────────────────────────────────────────────────
  {"id":"hf_aa_001","name":"Black Lion (Tikur Anbessa) Specialized Hospital","facility_type":"referral_hospital","region":"Addis Ababa","woreda":"Gulele","phone":"+251111239740","latitude":9.0350,"longitude":38.7614,"services":["Emergency","Surgery","ICU","Specialist care","Laboratory","Radiology","Blood bank","Oncology","Cardiology"],"hew_available":False,"distance_note_en":"National referral hospital — for complex cases only","distance_note_am":"ብሔራዊ ሪፈራል ሆስፒታል"},
  {"id":"hf_aa_002","name":"St. Paul's Hospital Millennium Medical College","facility_type":"referral_hospital","region":"Addis Ababa","woreda":"Gulele","phone":"+251111278100","latitude":9.0456,"longitude":38.7401,"services":["Emergency","Surgery","ICU","Maternity","Specialist care","Laboratory","Radiology"],"hew_available":False,"distance_note_en":"National referral hospital","distance_note_am":"ብሔራዊ ሪፈራል ሆስፒታል"},
  {"id":"hf_aa_003","name":"Yekatit 12 Hospital Medical College","facility_type":"hospital","region":"Addis Ababa","woreda":"Arada","phone":"+251111560444","latitude":9.0302,"longitude":38.7469,"services":["Emergency","Surgery","OPD","Maternity","Laboratory","HIV/ART"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  {"id":"hf_aa_004","name":"Zewditu Memorial Hospital","facility_type":"hospital","region":"Addis Ababa","woreda":"Kirkos","phone":"+251111553400","latitude":9.0142,"longitude":38.7614,"services":["Emergency","OPD","Maternity","Laboratory","HIV/ART","TB"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  {"id":"hf_aa_005","name":"Ras Desta Damtew Memorial Hospital","facility_type":"hospital","region":"Addis Ababa","woreda":"Bole","phone":"+251116629700","latitude":8.9956,"longitude":38.7969,"services":["Emergency","Surgery","OPD","Maternity","Laboratory"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  {"id":"hf_aa_006","name":"Bole Sub-City Health Center","facility_type":"health_center","region":"Addis Ababa","woreda":"Bole","phone":"+251116620011","latitude":9.0054,"longitude":38.8090,"services":["OPD","ANC","Delivery","Malaria testing","TB testing","HIV testing","Under-5 clinic","Family planning"],"hew_available":True,"distance_note_en":"Urban health center","distance_note_am":"የከተማ ጤና ጣቢያ"},
  {"id":"hf_aa_007","name":"Kirkos Sub-City Health Center","facility_type":"health_center","region":"Addis Ababa","woreda":"Kirkos","phone":"+251115570022","latitude":9.0142,"longitude":38.7500,"services":["OPD","ANC","Delivery","HIV/ART","TB","Family planning"],"hew_available":True,"distance_note_en":"Urban health center","distance_note_am":"የከተማ ጤና ጣቢያ"},
  {"id":"hf_aa_008","name":"Nifas Silk Lafto Health Center","facility_type":"health_center","region":"Addis Ababa","woreda":"Nifas Silk Lafto","phone":"+251114700033","latitude":8.9800,"longitude":38.7300,"services":["OPD","ANC","Delivery","Immunization","Nutrition","Family planning"],"hew_available":True,"distance_note_en":"Urban health center","distance_note_am":"የከተማ ጤና ጣቢያ"},
  # ── Oromia Region ─────────────────────────────────────────────────────────────
  {"id":"hf_or_001","name":"Jimma University Medical Center","facility_type":"referral_hospital","region":"Oromia","woreda":"Jimma","phone":"+251471110006","latitude":7.6731,"longitude":36.8344,"services":["Emergency","Surgery","ICU","Specialist care","HIV/ART","Laboratory","Radiology","Oncology"],"hew_available":False,"distance_note_en":"Regional referral hospital — for complex cases only","distance_note_am":"የክልል ሪፈራል ሆስፒታል"},
  {"id":"hf_or_002","name":"Adama Hospital Medical College","facility_type":"hospital","region":"Oromia","woreda":"Adama","phone":"+251222110044","latitude":8.5400,"longitude":39.2700,"services":["Emergency","Surgery","OPD","Maternity","Laboratory","HIV/ART","TB"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  {"id":"hf_or_003","name":"Nekemte Referral Hospital","facility_type":"referral_hospital","region":"Oromia","woreda":"Nekemte","phone":"+251576610055","latitude":9.0833,"longitude":36.5500,"services":["Emergency","Surgery","ICU","OPD","Maternity","Laboratory","Blood bank"],"hew_available":False,"distance_note_en":"Regional referral hospital","distance_note_am":"የክልል ሪፈራል ሆስፒታል"},
  {"id":"hf_or_004","name":"Shashemene Referral Hospital","facility_type":"referral_hospital","region":"Oromia","woreda":"Shashemene","phone":"+251462100066","latitude":7.2000,"longitude":38.5833,"services":["Emergency","Surgery","OPD","Maternity","Laboratory","HIV/ART"],"hew_available":False,"distance_note_en":"Regional referral hospital","distance_note_am":"የክልል ሪፈራል ሆስፒታል"},
  {"id":"hf_or_005","name":"Woliso Primary Hospital","facility_type":"primary_hospital","region":"Oromia","woreda":"Woliso","phone":"+251113400004","latitude":8.5300,"longitude":37.9800,"services":["Emergency","Surgery","OPD","Maternity","Laboratory","Blood bank"],"hew_available":False,"distance_note_en":"District hospital","distance_note_am":"የወረዳ ሆስፒታል"},
  {"id":"hf_or_006","name":"Arsi Negele Health Center","facility_type":"health_center","region":"Oromia","woreda":"Arsi Negele","phone":"+251462300003","latitude":7.3600,"longitude":38.6900,"services":["OPD","ANC","Delivery","Malaria testing","TB testing","Under-5 clinic","Nutrition"],"hew_available":True,"distance_note_en":"Referral point for surrounding health posts","distance_note_am":"ለአካባቢ ጤና ኬላዎች የሪፈራል ጣቢያ"},
  {"id":"hf_or_007","name":"Kuyu Primary Health Center","facility_type":"health_center","region":"Oromia","woreda":"Kuyu","phone":"+251111200001","latitude":9.4500,"longitude":38.1800,"services":["OPD","ANC","Delivery","Malaria testing","TB testing","HIV testing","Under-5 clinic"],"hew_available":True,"distance_note_en":"Referral point for surrounding health posts","distance_note_am":"ለአካባቢ ጤና ኬላዎች የሪፈራል ጣቢያ"},
  {"id":"hf_or_008","name":"Adama Health Center","facility_type":"health_center","region":"Oromia","woreda":"Adama","phone":"+251222110001","latitude":8.5400,"longitude":39.2700,"services":["OPD","ANC","Delivery","Malaria testing","TB testing","Family planning"],"hew_available":False,"distance_note_en":"Urban health center","distance_note_am":"የከተማ ጤና ጣቢያ"},
  {"id":"hf_or_009","name":"Kuyu Kebele Health Post","facility_type":"health_post","region":"Oromia","woreda":"Kuyu","kebele":"Kuyu 01","phone":"+251911100001","latitude":9.4200,"longitude":38.1500,"services":["Immunization","ANC","Family planning","Health education","Malaria RDT","ORS distribution"],"hew_available":True,"distance_note_en":"Serves surrounding rural kebeles within 5km","distance_note_am":"በ5 ኪሎሜትር ርቀት ውስጥ ያሉ ቀበሌዎችን ያገለግላል"},
  {"id":"hf_or_010","name":"Bale Robe General Hospital","facility_type":"hospital","region":"Oromia","woreda":"Bale Robe","phone":"+251220660077","latitude":7.1167,"longitude":40.0000,"services":["Emergency","Surgery","OPD","Maternity","Laboratory","HIV/ART"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  {"id":"hf_or_011","name":"Gimbi General Hospital","facility_type":"hospital","region":"Oromia","woreda":"Gimbi","phone":"+251577780088","latitude":9.1667,"longitude":35.8333,"services":["Emergency","OPD","Maternity","Laboratory","TB","HIV/ART"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  # ── Amhara Region ─────────────────────────────────────────────────────────────
  {"id":"hf_am_001","name":"Gondar University Comprehensive Specialized Hospital","facility_type":"referral_hospital","region":"Amhara","woreda":"Gondar","phone":"+251581140007","latitude":12.6030,"longitude":37.4521,"services":["Emergency","Surgery","ICU","Specialist care","Laboratory","Radiology","Blood bank","Oncology"],"hew_available":False,"distance_note_en":"Regional referral hospital","distance_note_am":"የክልል ሪፈራል ሆስፒታል"},
  {"id":"hf_am_002","name":"Felege Hiwot Referral Hospital","facility_type":"referral_hospital","region":"Amhara","woreda":"Bahir Dar","phone":"+251582200099","latitude":11.5936,"longitude":37.3906,"services":["Emergency","Surgery","ICU","OPD","Maternity","Laboratory","HIV/ART"],"hew_available":False,"distance_note_en":"Regional referral hospital","distance_note_am":"የክልል ሪፈራል ሆስፒታል"},
  {"id":"hf_am_003","name":"Debre Markos Referral Hospital","facility_type":"referral_hospital","region":"Amhara","woreda":"Debre Markos","phone":"+251587710110","latitude":10.3333,"longitude":37.7167,"services":["Emergency","Surgery","OPD","Maternity","Laboratory","HIV/ART","TB"],"hew_available":False,"distance_note_en":"Regional referral hospital","distance_note_am":"የክልል ሪፈራል ሆስፒታል"},
  {"id":"hf_am_004","name":"Debre Tabor Primary Hospital","facility_type":"primary_hospital","region":"Amhara","woreda":"Debre Tabor","phone":"+251582500005","latitude":11.8500,"longitude":38.0200,"services":["Emergency","Surgery","OPD","Maternity","Laboratory"],"hew_available":False,"distance_note_en":"District hospital","distance_note_am":"የወረዳ ሆስፒታል"},
  {"id":"hf_am_005","name":"Fogera Woreda Health Center","facility_type":"health_center","region":"Amhara","woreda":"Fogera","phone":"+251581300002","latitude":11.9700,"longitude":37.6900,"services":["OPD","ANC","Delivery","Malaria testing","TB testing","HIV/ART","Emergency"],"hew_available":True,"distance_note_en":"Referral point for surrounding health posts","distance_note_am":"ለአካባቢ ጤና ኬላዎች የሪፈራል ጣቢያ"},
  {"id":"hf_am_006","name":"Liben Jawi Kebele Health Post","facility_type":"health_post","region":"Amhara","woreda":"Liben Jawi","kebele":"Liben 02","phone":"+251911100002","latitude":11.2000,"longitude":36.9000,"services":["Immunization","ANC","Family planning","Health education","ORS distribution"],"hew_available":True,"distance_note_en":"Serves surrounding rural kebeles within 5km","distance_note_am":"በ5 ኪሎሜትር ርቀት ውስጥ ያሉ ቀበሌዎችን ያገለግላል"},
  {"id":"hf_am_007","name":"Dera Woreda Health Post","facility_type":"health_post","region":"Amhara","woreda":"Dera","kebele":"Dera 03","phone":"+251911100004","latitude":11.8500,"longitude":37.6500,"services":["Immunization","ANC","Family planning","TB screening","ORS distribution"],"hew_available":True,"distance_note_en":"Serves surrounding rural kebeles within 5km","distance_note_am":"በ5 ኪሎሜትር ርቀት ውስጥ ያሉ ቀበሌዎችን ያገለግላል"},
  {"id":"hf_am_008","name":"Dessie Referral Hospital","facility_type":"referral_hospital","region":"Amhara","woreda":"Dessie","phone":"+251331100120","latitude":11.1333,"longitude":39.6333,"services":["Emergency","Surgery","ICU","OPD","Maternity","Laboratory","HIV/ART"],"hew_available":False,"distance_note_en":"Regional referral hospital","distance_note_am":"የክልል ሪፈራል ሆስፒታል"},
  {"id":"hf_am_009","name":"Woldia General Hospital","facility_type":"hospital","region":"Amhara","woreda":"Woldia","phone":"+251331600130","latitude":11.8167,"longitude":39.6000,"services":["Emergency","OPD","Maternity","Laboratory","HIV/ART","TB"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  # ── Tigray Region ─────────────────────────────────────────────────────────────
  {"id":"hf_ti_001","name":"Ayder Comprehensive Specialized Hospital","facility_type":"referral_hospital","region":"Tigray","woreda":"Mekelle","phone":"+251344416140","latitude":13.4967,"longitude":39.4753,"services":["Emergency","Surgery","ICU","Specialist care","Laboratory","Radiology","Oncology","HIV/ART"],"hew_available":False,"distance_note_en":"Regional referral hospital","distance_note_am":"የክልል ሪፈራል ሆስፒታል"},
  {"id":"hf_ti_002","name":"Mekelle General Hospital","facility_type":"hospital","region":"Tigray","woreda":"Mekelle","phone":"+251344400004","latitude":13.4967,"longitude":39.4753,"services":["Emergency","Surgery","OPD","Maternity","Laboratory","HIV/ART"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  {"id":"hf_ti_003","name":"Axum General Hospital","facility_type":"hospital","region":"Tigray","woreda":"Axum","phone":"+251347750150","latitude":14.1200,"longitude":38.7200,"services":["Emergency","OPD","Maternity","Laboratory","HIV/ART","TB"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  {"id":"hf_ti_004","name":"Adwa General Hospital","facility_type":"hospital","region":"Tigray","woreda":"Adwa","phone":"+251347740160","latitude":14.1667,"longitude":38.9000,"services":["Emergency","OPD","Maternity","Laboratory","TB","HIV/ART"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  {"id":"hf_ti_005","name":"Shire Endaselassie Hospital","facility_type":"hospital","region":"Tigray","woreda":"Shire","phone":"+251347770170","latitude":14.1000,"longitude":38.2833,"services":["Emergency","OPD","Maternity","Laboratory","HIV/ART"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  # ── SNNPR Region ──────────────────────────────────────────────────────────────
  {"id":"hf_sn_001","name":"Hawassa University Comprehensive Specialized Hospital","facility_type":"referral_hospital","region":"SNNPR","woreda":"Hawassa","phone":"+251462200003","latitude":7.0621,"longitude":38.4768,"services":["Emergency","Surgery","ICU","Specialist care","Laboratory","Radiology","HIV/ART","Oncology"],"hew_available":False,"distance_note_en":"Regional referral hospital","distance_note_am":"የክልል ሪፈራል ሆስፒታል"},
  {"id":"hf_sn_002","name":"Yirgalem Primary Hospital","facility_type":"primary_hospital","region":"SNNPR","woreda":"Yirgalem","phone":"+251462600006","latitude":6.7500,"longitude":38.4000,"services":["Emergency","OPD","Maternity","Laboratory","HIV/ART"],"hew_available":False,"distance_note_en":"District hospital","distance_note_am":"የወረዳ ሆስፒታል"},
  {"id":"hf_sn_003","name":"Arba Minch General Hospital","facility_type":"hospital","region":"SNNPR","woreda":"Arba Minch","phone":"+251468810180","latitude":6.0333,"longitude":37.5500,"services":["Emergency","Surgery","OPD","Maternity","Laboratory","HIV/ART","TB"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  {"id":"hf_sn_004","name":"Wolaita Sodo University Referral Hospital","facility_type":"referral_hospital","region":"SNNPR","woreda":"Wolaita Sodo","phone":"+251465510190","latitude":6.8500,"longitude":37.7500,"services":["Emergency","Surgery","ICU","OPD","Maternity","Laboratory","HIV/ART"],"hew_available":False,"distance_note_en":"Regional referral hospital","distance_note_am":"የክልል ሪፈራል ሆስፒታል"},
  {"id":"hf_sn_005","name":"Damot Gale Kebele Health Post","facility_type":"health_post","region":"SNNPR","woreda":"Damot Gale","kebele":"Damot 01","phone":"+251911100003","latitude":6.9500,"longitude":37.8000,"services":["Immunization","ANC","Delivery","Family planning","Malaria RDT"],"hew_available":True,"distance_note_en":"Serves surrounding rural kebeles within 5km","distance_note_am":"በ5 ኪሎሜትር ርቀት ውስጥ ያሉ ቀበሌዎችን ያገለግላል"},
  {"id":"hf_sn_006","name":"Dilla University Referral Hospital","facility_type":"referral_hospital","region":"SNNPR","woreda":"Dilla","phone":"+251462420200","latitude":6.4100,"longitude":38.3100,"services":["Emergency","Surgery","OPD","Maternity","Laboratory","HIV/ART","TB"],"hew_available":False,"distance_note_en":"Regional referral hospital","distance_note_am":"የክልል ሪፈራል ሆስፒታል"},
  # ── Somali Region ─────────────────────────────────────────────────────────────
  {"id":"hf_so_001","name":"Jijiga Regional Hospital","facility_type":"hospital","region":"Somali","woreda":"Jijiga","phone":"+251257000010","latitude":9.3500,"longitude":42.7900,"services":["Emergency","OPD","Maternity","Laboratory","HIV/ART"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  {"id":"hf_so_002","name":"Jigjiga Health Center","facility_type":"health_center","region":"Somali","woreda":"Jijiga","phone":"+251257001210","latitude":9.3600,"longitude":42.8000,"services":["OPD","ANC","Delivery","Malaria testing","TB testing","HIV testing"],"hew_available":True,"distance_note_en":"Urban health center","distance_note_am":"የከተማ ጤና ጣቢያ"},
  {"id":"hf_so_003","name":"Gode General Hospital","facility_type":"hospital","region":"Somali","woreda":"Gode","phone":"+251255500220","latitude":5.9500,"longitude":43.5000,"services":["Emergency","OPD","Maternity","Laboratory","Malaria testing"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  # ── Afar Region ───────────────────────────────────────────────────────────────
  {"id":"hf_af_001","name":"Semera Referral Hospital","facility_type":"referral_hospital","region":"Afar","woreda":"Semera","phone":"+251336600230","latitude":11.7833,"longitude":41.0167,"services":["Emergency","Surgery","OPD","Maternity","Laboratory","HIV/ART","Malaria testing"],"hew_available":False,"distance_note_en":"Regional referral hospital","distance_note_am":"የክልል ሪፈራል ሆስፒታል"},
  {"id":"hf_af_002","name":"Dubti General Hospital","facility_type":"hospital","region":"Afar","woreda":"Dubti","phone":"+251336610240","latitude":11.7167,"longitude":41.0833,"services":["Emergency","OPD","Maternity","Laboratory","Malaria testing","HIV/ART"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  # ── Dire Dawa ─────────────────────────────────────────────────────────────────
  {"id":"hf_dd_001","name":"Dilchora Referral Hospital","facility_type":"referral_hospital","region":"Dire Dawa","woreda":"Dire Dawa","phone":"+251251110250","latitude":9.5931,"longitude":41.8661,"services":["Emergency","Surgery","ICU","OPD","Maternity","Laboratory","HIV/ART","TB"],"hew_available":False,"distance_note_en":"Regional referral hospital","distance_note_am":"የክልል ሪፈራል ሆስፒታል"},
  {"id":"hf_dd_002","name":"Dire Dawa Health Center","facility_type":"health_center","region":"Dire Dawa","woreda":"Dire Dawa","phone":"+251251000009","latitude":9.5931,"longitude":41.8661,"services":["OPD","ANC","Delivery","Emergency","HIV testing","TB testing"],"hew_available":False,"distance_note_en":"Urban health center","distance_note_am":"የከተማ ጤና ጣቢያ"},
  # ── Harari Region ─────────────────────────────────────────────────────────────
  {"id":"hf_hr_001","name":"Hiwot Fana Specialized University Hospital","facility_type":"referral_hospital","region":"Harari","woreda":"Harar","phone":"+251256660260","latitude":9.3133,"longitude":42.1200,"services":["Emergency","Surgery","ICU","OPD","Maternity","Laboratory","HIV/ART","Specialist care"],"hew_available":False,"distance_note_en":"Regional referral hospital","distance_note_am":"የክልል ሪፈራል ሆስፒታል"},
  {"id":"hf_hr_002","name":"Jugol Hospital","facility_type":"hospital","region":"Harari","woreda":"Harar","phone":"+251256660270","latitude":9.3100,"longitude":42.1300,"services":["Emergency","OPD","Maternity","Laboratory","HIV/ART"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  # ── Gambella Region ───────────────────────────────────────────────────────────
  {"id":"hf_ga_001","name":"Gambella General Hospital","facility_type":"hospital","region":"Gambella","woreda":"Gambella","phone":"+251477700280","latitude":8.2500,"longitude":34.5833,"services":["Emergency","OPD","Maternity","Laboratory","Malaria testing","HIV/ART"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  # ── Benishangul-Gumuz ─────────────────────────────────────────────────────────
  {"id":"hf_bg_001","name":"Assosa General Hospital","facility_type":"hospital","region":"Benishangul-Gumuz","woreda":"Assosa","phone":"+251578400290","latitude":10.0667,"longitude":34.5333,"services":["Emergency","OPD","Maternity","Laboratory","Malaria testing","HIV/ART","TB"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  # ── Sidama Region ─────────────────────────────────────────────────────────────
  {"id":"hf_si_001","name":"Hawassa Adare General Hospital","facility_type":"hospital","region":"Sidama","woreda":"Hawassa","phone":"+251462210300","latitude":7.0500,"longitude":38.4800,"services":["Emergency","OPD","Maternity","Laboratory","HIV/ART","TB"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  # ── South West Ethiopia ───────────────────────────────────────────────────────
  {"id":"hf_sw_001","name":"Mizan-Aman General Hospital","facility_type":"hospital","region":"South West Ethiopia","woreda":"Mizan-Aman","phone":"+251478300310","latitude":6.9833,"longitude":35.5667,"services":["Emergency","OPD","Maternity","Laboratory","HIV/ART","Malaria testing"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
  {"id":"hf_sw_002","name":"Tepi General Hospital","facility_type":"hospital","region":"South West Ethiopia","woreda":"Tepi","phone":"+251478310320","latitude":7.2000,"longitude":35.4667,"services":["Emergency","OPD","Maternity","Laboratory","Malaria testing"],"hew_available":False,"distance_note_en":"Urban hospital","distance_note_am":"የከተማ ሆስፒታል"},
]

d['facilities'] = FACILITIES
with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(d, f, ensure_ascii=False, indent=2)
print(f"Done. Added {len(FACILITIES)} facilities.")
