import json, os
PATH = os.path.join(os.path.dirname(__file__), '..', 'data', 'knowledge_base.json')
d = json.load(open(PATH, encoding='utf-8'))

MEDS = []

MEDS += [
  {"id":"paracetamol","name_en":"Paracetamol (Acetaminophen)","name_am":"ፓራሲታሞል","generic_name":"paracetamol","category":"analgesic_antipyretic","aliases":["panadol","acetaminophen","tylenol"],"used_for_conditions":["malaria","upper_respiratory","childhood_fever","burns"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":False,
   "description_en":"Paracetamol is the first-line drug for fever and mild-to-moderate pain. Safe for all ages including pregnant women and children when used at correct doses. Does NOT reduce inflammation.",
   "description_am":"ፓራሲታሞል ለትኩሳት እና ቀላል ህመም ዋና መድሃኒት ነው። ለሁሉም ዕድሜ ደህንነቱ የተጠበቀ ነው።",
   "dosage_adult_en":"500-1000mg every 4-6 hours. Maximum 4000mg per day (4g/day). Do not exceed.",
   "dosage_adult_am":"500-1000 ሚሊ ግራም በ4-6 ሰዓት ልዩነት። በቀን ከ4000 ሚሊ ግራም አይበልጥ።",
   "dosage_child_en":"10-15mg/kg every 4-6 hours. Max 5 doses in 24 hours. Example: 10kg child = 100-150mg per dose.",
   "dosage_child_am":"10-15 ሚሊ ግራም/ኪሎ ግራም በ4-6 ሰዓት ልዩነት።",
   "side_effects_en":"Rare at normal doses. Overdose causes severe liver damage. Do not combine with alcohol.",
   "contraindications_en":"Severe liver disease. Alcohol dependence. Do not exceed recommended dose.",
   "warnings_en":"NEVER give aspirin to children under 16 — use paracetamol instead. Overdose is a medical emergency."},

  {"id":"amoxicillin","name_en":"Amoxicillin","name_am":"አሞክሲሲሊን","generic_name":"amoxicillin","category":"antibiotic_penicillin","aliases":["amoxil","trimox"],"used_for_conditions":["pneumonia","urinary_tract_infection","skin_infection","ear_infection"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Amoxicillin is a broad-spectrum penicillin antibiotic. First-line for pneumonia, ear infections, UTIs, and skin infections. Must complete the full course even if feeling better.",
   "description_am":"አሞክሲሲሊን ሰፊ ስፔክትረም ፔኒሲሊን አንቲባዮቲክ ነው። ሙሉ ኮርስ ሳያቋርጡ ይውሰዱ።",
   "dosage_adult_en":"500mg three times daily for 5-7 days. For severe infections: 875mg twice daily.",
   "dosage_adult_am":"500 ሚሊ ግራም በቀን 3 ጊዜ ለ5-7 ቀናት።",
   "dosage_child_en":"25-45mg/kg/day divided into 2-3 doses. For pneumonia: 40mg/kg/day in 2 doses.",
   "dosage_child_am":"25-45 ሚሊ ግራም/ኪሎ ግራም/ቀን በ2-3 ክፍሎች።",
   "side_effects_en":"Diarrhea, nausea, rash. Allergic reaction (rare but serious — stop immediately if rash or breathing difficulty).",
   "contraindications_en":"Penicillin allergy. Use with caution in kidney disease.",
   "warnings_en":"Always complete the full antibiotic course. Stopping early causes antibiotic resistance."},
]

MEDS += [
  {"id":"ors","name_en":"Oral Rehydration Salts (ORS)","name_am":"ORS (የአፍ ድርቀት መፍትሄ)","generic_name":"oral rehydration salts","category":"rehydration","aliases":["ors","oral rehydration solution","rehydration salts"],"used_for_conditions":["diarrhea","cholera"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":False,
   "description_en":"ORS is the cornerstone treatment for dehydration from diarrhea. A simple mixture of sugar, salt, and water that replaces fluids and electrolytes lost during diarrhea. Saves millions of lives annually.",
   "description_am":"ORS ከተቅማጥ ለሚከሰት ድርቀት ዋና ህክምና ነው። ስኳር፣ ጨው እና ውሃ ድብልቅ ነው።",
   "dosage_adult_en":"Dissolve 1 ORS sachet in 1 litre of clean water. Drink 200-400ml after each loose stool. For cholera: up to 1 litre/hour. Home recipe: 1L water + 6 tsp sugar + 0.5 tsp salt.",
   "dosage_adult_am":"1 ORS ፓኬት በ1 ሊትር ንጹህ ውሃ ይቀልቡ። ከእያንዳንዱ ተቅማጥ በኋላ 200-400 ሚሊ ሊትር ይጠጡ።",
   "dosage_child_en":"Under 2 years: 50-100ml after each loose stool. 2-10 years: 100-200ml after each stool. Continue breastfeeding.",
   "dosage_child_am":"ከ2 ዓመት በታች: ከእያንዳንዱ ተቅማጥ በኋላ 50-100 ሚሊ ሊትር።",
   "side_effects_en":"None when used correctly. Vomiting may occur — give small sips slowly.",
   "contraindications_en":"Severe dehydration with shock requires IV fluids, not ORS alone.",
   "warnings_en":"If child cannot drink or is unconscious, go to health centre immediately for IV fluids."},

  {"id":"artemether_lumefantrine","name_en":"Artemether-Lumefantrine (Coartem)","name_am":"አርቴሜተር-ሉሜፋንትሪን (ኮርቴም)","generic_name":"artemether-lumefantrine","category":"antimalarial","aliases":["coartem","al","act"],"used_for_conditions":["malaria"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Artemether-lumefantrine (AL) is the first-line artemisinin-based combination therapy (ACT) for uncomplicated malaria in Ethiopia. Must be taken with food or milk for proper absorption. Complete the full 3-day course.",
   "description_am":"አርቴሜተር-ሉሜፋንትሪን ኢትዮጵያ ውስጥ ለቀላል ወባ ዋና ህክምና ነው። ሙሉ 3 ቀን ኮርስ ሳያቋርጡ ይውሰዱ።",
   "dosage_adult_en":"Adults and children over 35kg: 4 tablets at 0, 8, 24, 36, 48, 60 hours (6 doses total over 3 days). Take with food.",
   "dosage_adult_am":"ከ35 ኪሎ ግራም በላይ: 4 ጡባዊ በ0፣ 8፣ 24፣ 36፣ 48፣ 60 ሰዓት (6 ጊዜ ለ3 ቀናት)። ከምግብ ጋር ይውሰዱ።",
   "dosage_child_en":"5-14kg: 1 tablet per dose. 15-24kg: 2 tablets per dose. 25-34kg: 3 tablets per dose. Same 6-dose schedule.",
   "dosage_child_am":"5-14 ኪሎ ግራም: 1 ጡባዊ። 15-24 ኪሎ ግራም: 2 ጡባዊ። 25-34 ኪሎ ግራም: 3 ጡባዊ።",
   "side_effects_en":"Headache, dizziness, nausea, vomiting, abdominal pain, fatigue. Usually mild and resolve after treatment.",
   "contraindications_en":"First trimester of pregnancy (use quinine instead). Severe malaria (use IV artesunate). Known hypersensitivity.",
   "warnings_en":"Do NOT use for severe malaria — requires IV artesunate in hospital. Always confirm malaria with RDT before treating."},

  {"id":"cotrimoxazole","name_en":"Cotrimoxazole (Trimethoprim-Sulfamethoxazole)","name_am":"ኮትሪሞክሳዞል","generic_name":"trimethoprim-sulfamethoxazole","category":"antibiotic","aliases":["septrin","bactrim","tmp-smx","co-trimoxazole"],"used_for_conditions":["urinary_tract_infection","pneumonia","hiv_aids"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Cotrimoxazole is a combination antibiotic used for UTIs, pneumonia (including PCP in HIV patients), and as prophylaxis for HIV-positive patients with low CD4 counts. Very affordable and widely available in Ethiopia.",
   "description_am":"ኮትሪሞክሳዞል ለሽንት ቱቦ ኢንፌክሽን፣ ሳምባ ምች እና ኤች አይ ቪ ታካሚዎች ጥቅም ላይ ይውላል።",
   "dosage_adult_en":"UTI: 960mg (2 standard tablets) twice daily for 3-7 days. HIV prophylaxis: 960mg once daily.",
   "dosage_adult_am":"ሽንት ቱቦ ኢንፌክሽን: 960 ሚሊ ግራም በቀን 2 ጊዜ ለ3-7 ቀናት።",
   "dosage_child_en":"6 weeks-5 months: 120mg twice daily. 6 months-5 years: 240mg twice daily. 6-12 years: 480mg twice daily.",
   "dosage_child_am":"6 ሳምንት-5 ወር: 120 ሚሊ ግራም በቀን 2 ጊዜ።",
   "side_effects_en":"Nausea, rash, photosensitivity. Rare but serious: Stevens-Johnson syndrome (severe rash — stop immediately).",
   "contraindications_en":"Sulfa allergy. Severe kidney or liver disease. Third trimester of pregnancy. Newborns under 6 weeks.",
   "warnings_en":"Drink plenty of water while taking. Stop immediately if severe rash develops."},
]

MEDS += [
  {"id":"metronidazole","name_en":"Metronidazole (Flagyl)","name_am":"ሜትሮኒዳዞል","generic_name":"metronidazole","category":"antibiotic_antiparasitic","aliases":["flagyl","metrogyl"],"used_for_conditions":["diarrhea","peptic_ulcer","tetanus","skin_infection"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Metronidazole treats anaerobic bacterial infections, parasitic infections (Giardia, Entamoeba, Trichomonas), and is part of H. pylori eradication therapy for peptic ulcers.",
   "description_am":"ሜትሮኒዳዞል ጥገኛ ተሕዋስያን ኢንፌክሽን እና ሌሎች ኢንፌክሽኖችን ያክማል።",
   "dosage_adult_en":"Giardia/Entamoeba: 400-500mg three times daily for 5-7 days. H. pylori: 400mg twice daily for 14 days (with other drugs). Anaerobic infections: 400mg three times daily for 7 days.",
   "dosage_adult_am":"400-500 ሚሊ ግራም በቀን 3 ጊዜ ለ5-7 ቀናት።",
   "dosage_child_en":"7.5mg/kg three times daily for 5-7 days.",
   "dosage_child_am":"7.5 ሚሊ ግራም/ኪሎ ግራም በቀን 3 ጊዜ ለ5-7 ቀናት።",
   "side_effects_en":"Nausea, metallic taste, headache, dizziness. Dark urine (harmless).",
   "contraindications_en":"First trimester of pregnancy. Do NOT drink alcohol during treatment and for 48 hours after — causes severe nausea and vomiting.",
   "warnings_en":"Avoid alcohol completely during treatment. Complete the full course."},

  {"id":"albendazole","name_en":"Albendazole","name_am":"አልቤንዳዞል","generic_name":"albendazole","category":"antiparasitic_anthelmintic","aliases":["zentel","albenza"],"used_for_conditions":["hookworm","schistosomiasis"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":False,
   "description_en":"Albendazole is used to treat intestinal worm infections including hookworm, roundworm, whipworm, and pinworm. Also used for neurocysticercosis (tapeworm in brain). Available free in Ethiopia's mass deworming programmes.",
   "description_am":"አልቤንዳዞል የሆድ ትሎችን ለማከም ጥቅም ላይ ይውላል። በኢትዮጵያ ነፃ ይሰጣል።",
   "dosage_adult_en":"Intestinal worms: 400mg single dose. Neurocysticercosis: 400mg twice daily for 8-30 days with steroids.",
   "dosage_adult_am":"400 ሚሊ ግራም አንድ ጊዜ።",
   "dosage_child_en":"Over 2 years: 400mg single dose. Under 2 years: 200mg single dose.",
   "dosage_child_am":"ከ2 ዓመት በላይ: 400 ሚሊ ግራም አንድ ጊዜ።",
   "side_effects_en":"Usually well tolerated. Mild nausea, abdominal pain. Rarely: headache, dizziness.",
   "contraindications_en":"Pregnancy (first trimester). Liver disease.",
   "warnings_en":"Repeat dose after 2 weeks for heavy infections. Take with food for better absorption."},

  {"id":"ferrous_sulfate","name_en":"Ferrous Sulfate (Iron Supplement)","name_am":"ፌሮስ ሰልፌት (የብረት ተጨማሪ)","generic_name":"ferrous sulfate","category":"nutritional_supplement","aliases":["iron tablet","iron supplement"],"used_for_conditions":["anemia"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":False,
   "description_en":"Ferrous sulfate is the standard iron supplement for treating iron deficiency anaemia. Widely used in Ethiopia for pregnant women and children. Must be taken with vitamin C-rich foods to improve absorption.",
   "description_am":"ፌሮስ ሰልፌት የብረት እጥረት ደም ማነስን ለማከም ጥቅም ላይ ይውላል። ለእርጉዝ ሴቶች እና ህጻናት ይሰጣል።",
   "dosage_adult_en":"Treatment: 200mg (65mg elemental iron) 2-3 times daily. Prevention in pregnancy: 60mg elemental iron once daily with 400mcg folic acid.",
   "dosage_adult_am":"ህክምና: 200 ሚሊ ግራም በቀን 2-3 ጊዜ። ለእርጉዝ ሴቶች: 60 ሚሊ ግራም አንድ ጊዜ።",
   "dosage_child_en":"3-6mg/kg/day of elemental iron in 2-3 divided doses.",
   "dosage_child_am":"3-6 ሚሊ ግራም/ኪሎ ግራም/ቀን።",
   "side_effects_en":"Constipation, dark stools (harmless), nausea, stomach upset. Take with food to reduce nausea.",
   "contraindications_en":"Haemochromatosis (iron overload). Haemolytic anaemia without iron deficiency.",
   "warnings_en":"Take on empty stomach for best absorption, or with food if stomach upset. Avoid tea/coffee within 1 hour. Keep away from children — iron overdose is dangerous."},
]

MEDS += [
  {"id":"folic_acid","name_en":"Folic Acid","name_am":"ፎሊክ አሲድ","generic_name":"folic acid","category":"nutritional_supplement","aliases":["folate","vitamin b9"],"used_for_conditions":["anemia","obstetric_emergency","preeclampsia"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":False,
   "description_en":"Folic acid prevents neural tube defects in the baby when taken before and during early pregnancy. Also treats folate deficiency anaemia. All women of childbearing age should take folic acid.",
   "description_am":"ፎሊክ አሲድ ከእርግዝና በፊት እና በእርግዝና ወቅት ሲወሰድ የህጻን የነርቭ ቱቦ ጉድለቶችን ይከላከላል።",
   "dosage_adult_en":"Prevention of neural tube defects: 400mcg daily starting 1 month before conception and through first 12 weeks. Treatment of deficiency: 5mg daily for 4 months.",
   "dosage_adult_am":"የነርቭ ቱቦ ጉድለት መከላከል: 400 ማይክሮ ግራም በቀን።",
   "dosage_child_en":"Infants: 50mcg daily. Children 1-4 years: 100mcg daily.",
   "dosage_child_am":"ህጻናት: 50-100 ማይክሮ ግራም በቀን።",
   "side_effects_en":"Very safe. Rarely: nausea, bloating.",
   "contraindications_en":"High doses may mask vitamin B12 deficiency anaemia.",
   "warnings_en":"All pregnant women and women planning pregnancy should take folic acid. Combined iron-folic acid tablets available at health posts."},

  {"id":"magnesium_sulfate","name_en":"Magnesium Sulfate","name_am":"ማግኒዚየም ሰልፌት","generic_name":"magnesium sulfate","category":"obstetric_emergency","aliases":["mag sulfate","mgso4"],"used_for_conditions":["obstetric_emergency","preeclampsia"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Magnesium sulfate is the drug of choice for preventing and treating eclamptic seizures in pregnancy. It is a life-saving drug that must be available at all health centres. Reduces maternal mortality significantly.",
   "description_am":"ማግኒዚየም ሰልፌት በእርግዝና ወቅት ሽብርታን ለመከላከል እና ለማከም ዋና መድሃኒት ነው። ህይወት አድን መድሃኒት ነው።",
   "dosage_adult_en":"Loading dose: 4g IV over 15-20 minutes. Maintenance: 1g/hour IV infusion OR 5g IM every 4 hours. Continue for 24 hours after last seizure or delivery.",
   "dosage_adult_am":"ጅምር መጠን: 4 ግራም IV ለ15-20 ደቂቃ። ቀጣይ: 1 ግራም/ሰዓት IV።",
   "dosage_child_en":"Not used in children for this indication.",
   "dosage_child_am":"ለህጻናት አይሰጥም።",
   "side_effects_en":"Flushing, sweating, nausea. Toxicity signs: loss of deep tendon reflexes, respiratory depression, cardiac arrest.",
   "contraindications_en":"Myasthenia gravis. Renal failure (reduce dose). Monitor urine output, reflexes, and respiratory rate.",
   "warnings_en":"ANTIDOTE: Calcium gluconate 1g IV for toxicity. Monitor reflexes and breathing every 30 minutes. Keep antidote ready."},

  {"id":"oxytocin","name_en":"Oxytocin","name_am":"ኦክሲቶሲን","generic_name":"oxytocin","category":"uterotonic","aliases":["pitocin","syntocinon"],"used_for_conditions":["obstetric_emergency"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Oxytocin is the first-line drug for preventing and treating postpartum haemorrhage (PPH), the leading cause of maternal death. Given immediately after delivery of the baby. Every health facility must have oxytocin available.",
   "description_am":"ኦክሲቶሲን ከወሊድ በኋላ ደም መፍሰስን ለመከላከል እና ለማከም ዋና መድሃኒት ነው። ህጻኑ ከተወለደ ወዲያውኑ ይሰጣል።",
   "dosage_adult_en":"PPH prevention: 10 IU IM immediately after delivery. PPH treatment: 20-40 IU in 1L IV fluid at 40 drops/min. Induction: 0.5-2 mIU/min IV, titrate up.",
   "dosage_adult_am":"ከወሊድ በኋላ ደም መፍሰስ መከላከል: 10 IU IM ወዲያውኑ ከወሊድ በኋላ።",
   "dosage_child_en":"Not applicable.",
   "dosage_child_am":"ለህጻናት አይሰጥም።",
   "side_effects_en":"Uterine hyperstimulation, fetal distress if used for induction. Nausea, vomiting, headache.",
   "contraindications_en":"Obstructed labour. Fetal malpresentation. Previous uterine scar (use with caution).",
   "warnings_en":"Misoprostol 600mcg oral is an alternative when oxytocin is unavailable or no IV access."},

  {"id":"misoprostol","name_en":"Misoprostol","name_am":"ሚዞፕሮስቶል","generic_name":"misoprostol","category":"uterotonic","aliases":["cytotec"],"used_for_conditions":["obstetric_emergency","peptic_ulcer"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Misoprostol is a prostaglandin used for PPH prevention when oxytocin is unavailable, peptic ulcer treatment, and cervical ripening. Can be given orally, sublingually, or rectally — no refrigeration needed, making it ideal for rural settings.",
   "description_am":"ሚዞፕሮስቶል ኦክሲቶሲን ሲገኝ ካልቻለ ከወሊድ በኋላ ደም መፍሰስን ለመከላከል ጥቅም ላይ ይውላል። ቀዝቃዛ ቦታ አያስፈልገውም።",
   "dosage_adult_en":"PPH prevention: 600mcg oral or sublingual immediately after delivery. PPH treatment: 800mcg sublingual. Peptic ulcer: 200mcg four times daily with food.",
   "dosage_adult_am":"ከወሊድ በኋላ ደም መፍሰስ መከላከል: 600 ማይክሮ ግራም አፍ ውስጥ ወዲያውኑ ከወሊድ በኋላ።",
   "dosage_child_en":"Not applicable for obstetric use.",
   "dosage_child_am":"ለህጻናት አይሰጥም።",
   "side_effects_en":"Shivering, fever, nausea, diarrhea (usually transient). Higher doses cause more side effects.",
   "contraindications_en":"Previous caesarean section (for induction — risk of uterine rupture). Allergy to prostaglandins.",
   "warnings_en":"Ideal for community-level PPH prevention as it requires no refrigeration and no IV access."},
]

MEDS += [
  {"id":"salbutamol","name_en":"Salbutamol (Albuterol) Inhaler","name_am":"ሳልቡታሞል ኢንሃለር","generic_name":"salbutamol","category":"bronchodilator","aliases":["albuterol","ventolin","reliever inhaler"],"used_for_conditions":["asthma"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Salbutamol is a short-acting beta-2 agonist (SABA) — the reliever inhaler for asthma attacks. It relaxes airway muscles within minutes. Every asthma patient should carry it at all times.",
   "description_am":"ሳልቡታሞል ኢንሃለር የአስም ጥቃት ሲከሰት ወዲያውኑ ለማስታገስ ጥቅም ላይ ይውላል። ሁሉም የአስም ታካሚ ሁልጊዜ ይዞ መሄድ አለበት።",
   "dosage_adult_en":"Acute attack: 2-4 puffs every 20 minutes for first hour, then every 1-4 hours. Prevention before exercise: 2 puffs 15 minutes before.",
   "dosage_adult_am":"ጥቃት ሲከሰት: 2-4 ፓፍ በ20 ደቂቃ ልዩነት ለ1 ሰዓት።",
   "dosage_child_en":"Same as adult. Use spacer device for children under 5.",
   "dosage_child_am":"ከ5 ዓመት በታች ህጻናት ስፔሰር ይጠቀሙ።",
   "side_effects_en":"Tremor, palpitations, headache, nervousness. Usually mild and short-lived.",
   "contraindications_en":"No absolute contraindications for acute asthma. Use with caution in heart disease.",
   "warnings_en":"Reliever only — does NOT prevent attacks. If using more than 3 times/week, needs preventer inhaler. Overuse indicates poor asthma control."},

  {"id":"phenobarbital","name_en":"Phenobarbital","name_am":"ፊኖባርቢታል","generic_name":"phenobarbital","category":"antiepileptic","aliases":["phenobarbitone","luminal"],"used_for_conditions":["epilepsy"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Phenobarbital is the first-line antiepileptic drug in Ethiopia due to its low cost, effectiveness, and availability. Controls most types of seizures. Treatment is lifelong for most patients. Never stop suddenly.",
   "description_am":"ፊኖባርቢታል ኢትዮጵያ ውስጥ ለሚጥል በሽታ ዋና መድሃኒት ነው። ዝቅተኛ ዋጋ እና ውጤታማ ነው። ድንገት ማቆም አይቻልም።",
   "dosage_adult_en":"Starting: 60-180mg at night. Maintenance: 60-180mg/day. Adjust based on seizure control and side effects.",
   "dosage_adult_am":"ጅምር: 60-180 ሚሊ ግራም ማታ። ቀጣይ: 60-180 ሚሊ ግራም/ቀን።",
   "dosage_child_en":"3-5mg/kg/day in 1-2 doses. Neonatal seizures: 15-20mg/kg loading dose IV.",
   "dosage_child_am":"3-5 ሚሊ ግራም/ኪሎ ግራም/ቀን።",
   "side_effects_en":"Sedation (especially initially), hyperactivity in children, cognitive effects, osteoporosis with long-term use.",
   "contraindications_en":"Porphyria. Severe respiratory depression. Avoid in pregnancy if possible (teratogenic).",
   "warnings_en":"NEVER stop suddenly — causes withdrawal seizures. Taper slowly over weeks. Causes drowsiness — avoid driving."},

  {"id":"metformin","name_en":"Metformin","name_am":"ሜትፎርሚን","generic_name":"metformin","category":"antidiabetic","aliases":["glucophage","diabex"],"used_for_conditions":["diabetes"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Metformin is the first-line oral medication for type 2 diabetes. It lowers blood sugar by reducing liver glucose production and improving insulin sensitivity. Does not cause hypoglycaemia when used alone.",
   "description_am":"ሜትፎርሚን ለዓይነት 2 የስኳር በሽታ ዋና የአፍ መድሃኒት ነው። ብቻውን ሲወሰድ ዝቅተኛ የስኳር ደረጃ አያስከትልም።",
   "dosage_adult_en":"Starting: 500mg twice daily with meals. Increase gradually to 1000mg twice daily. Maximum: 2550mg/day.",
   "dosage_adult_am":"ጅምር: 500 ሚሊ ግራም ከምግብ ጋር በቀን 2 ጊዜ። ቀስ ብሎ ወደ 1000 ሚሊ ግራም ይጨምሩ።",
   "dosage_child_en":"Not recommended under 10 years. 10+ years: 500mg twice daily, max 2000mg/day.",
   "dosage_child_am":"ከ10 ዓመት በላይ: 500 ሚሊ ግራም በቀን 2 ጊዜ።",
   "side_effects_en":"Nausea, diarrhea, stomach upset (usually improve after 2-4 weeks). Lactic acidosis (rare but serious).",
   "contraindications_en":"Kidney disease (eGFR <30). Liver disease. Heart failure. Stop before contrast dye procedures.",
   "warnings_en":"Take with food to reduce stomach upset. Monitor kidney function annually. Stop if vomiting or dehydrated."},

  {"id":"enalapril","name_en":"Enalapril","name_am":"ኤናላፕሪል","generic_name":"enalapril","category":"ace_inhibitor_antihypertensive","aliases":["vasotec","renitec"],"used_for_conditions":["hypertension","heart_failure","diabetes"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Enalapril is an ACE inhibitor used for hypertension, heart failure, and diabetic kidney protection. Reduces blood pressure and protects the kidneys in diabetic patients. First-line for hypertension with diabetes or heart failure.",
   "description_am":"ኤናላፕሪል ለከፍተኛ የደም ግፊት፣ የልብ ውድቀት እና የስኳር ታካሚዎች ኩላሊት ጥበቃ ጥቅም ላይ ይውላል።",
   "dosage_adult_en":"Hypertension: 5mg once daily, increase to 10-40mg/day. Heart failure: 2.5mg twice daily, increase to 10-20mg twice daily.",
   "dosage_adult_am":"ከፍተኛ የደም ግፊት: 5 ሚሊ ግራም አንድ ጊዜ፣ ወደ 10-40 ሚሊ ግራም ይጨምሩ።",
   "dosage_child_en":"0.1mg/kg once daily, max 0.5mg/kg/day.",
   "dosage_child_am":"0.1 ሚሊ ግራም/ኪሎ ግራም አንድ ጊዜ።",
   "side_effects_en":"Dry cough (common — switch to ARB if intolerable), dizziness, elevated potassium, kidney function changes.",
   "contraindications_en":"PREGNANCY (causes fetal harm — stop immediately if pregnant). Bilateral renal artery stenosis. Angioedema history.",
   "warnings_en":"Monitor blood pressure, kidney function, and potassium. Do not use in pregnancy."},
]

MEDS += [
  {"id":"amlodipine","name_en":"Amlodipine","name_am":"አምሎዲፒን","generic_name":"amlodipine","category":"calcium_channel_blocker","aliases":["norvasc","istin"],"used_for_conditions":["hypertension"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Amlodipine is a calcium channel blocker used for hypertension and angina. Well tolerated, once-daily dosing, safe in most patients including elderly and those with kidney disease.",
   "description_am":"አምሎዲፒን ለከፍተኛ የደም ግፊት ጥቅም ላይ ይውላል። በቀን አንድ ጊዜ ይወሰዳል።",
   "dosage_adult_en":"5mg once daily. Can increase to 10mg once daily after 2 weeks if needed.",
   "dosage_adult_am":"5 ሚሊ ግራም አንድ ጊዜ። አስፈላጊ ከሆነ ወደ 10 ሚሊ ግራም ይጨምሩ።",
   "dosage_child_en":"6-17 years: 2.5-5mg once daily.",
   "dosage_child_am":"6-17 ዓመት: 2.5-5 ሚሊ ግራም አንድ ጊዜ።",
   "side_effects_en":"Ankle swelling (common), flushing, headache, palpitations. Usually mild.",
   "contraindications_en":"Cardiogenic shock. Severe aortic stenosis.",
   "warnings_en":"Do not stop suddenly. Take at the same time each day. Ankle swelling does not mean heart failure."},

  {"id":"doxycycline","name_en":"Doxycycline","name_am":"ዶክሲሳይክሊን","generic_name":"doxycycline","category":"antibiotic_tetracycline","aliases":["vibramycin","doxylin"],"used_for_conditions":["malaria","brucellosis","typhus","cholera"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Doxycycline is a broad-spectrum tetracycline antibiotic used for malaria prophylaxis, brucellosis, typhus, cholera, and many other infections. Also used for acne and sexually transmitted infections.",
   "description_am":"ዶክሲሳይክሊን ሰፊ ስፔክትረም አንቲባዮቲክ ሲሆን ለወባ መከላከያ፣ ብሩሴሎሲስ፣ ታይፈስ እና ሌሎች ኢንፌክሽኖች ጥቅም ላይ ይውላል።",
   "dosage_adult_en":"Malaria prophylaxis: 100mg daily starting 1-2 days before travel, during, and 4 weeks after. Brucellosis: 100mg twice daily for 6 weeks. Cholera: 300mg single dose.",
   "dosage_adult_am":"ወባ መከላከያ: 100 ሚሊ ግራም በቀን። ብሩሴሎሲስ: 100 ሚሊ ግራም በቀን 2 ጊዜ ለ6 ሳምንት።",
   "dosage_child_en":"NOT recommended under 8 years (causes permanent tooth discolouration). Over 8 years: 2-4mg/kg/day.",
   "dosage_child_am":"ከ8 ዓመት በታች አይሰጥም (ጥርስ ቀለም ይቀይራል)።",
   "side_effects_en":"Nausea, photosensitivity (avoid sun exposure), esophageal irritation (take with full glass of water, stay upright).",
   "contraindications_en":"Children under 8 years. Pregnancy. Breastfeeding.",
   "warnings_en":"Take with full glass of water and remain upright for 30 minutes. Use sunscreen. Do not take with antacids or dairy."},

  {"id":"praziquantel","name_en":"Praziquantel","name_am":"ፕራዚኳንቴል","generic_name":"praziquantel","category":"antiparasitic","aliases":["biltricide","cysticide"],"used_for_conditions":["schistosomiasis","hookworm"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":False,
   "description_en":"Praziquantel is the drug of choice for schistosomiasis (bilharzia) and tapeworm infections. Available free in Ethiopia's mass drug administration programmes. Single dose is usually curative.",
   "description_am":"ፕራዚኳንቴል ሺስቶሶሚያሲስ እና ቴፕዎርም ኢንፌክሽን ዋና መድሃኒት ነው። ኢትዮጵያ ውስጥ ነፃ ይሰጣል።",
   "dosage_adult_en":"Schistosomiasis: 40mg/kg as single dose or split into 2 doses 4-6 hours apart. Tapeworm: 5-10mg/kg single dose.",
   "dosage_adult_am":"ሺስቶሶሚያሲስ: 40 ሚሊ ግራም/ኪሎ ግራም አንድ ጊዜ።",
   "dosage_child_en":"Same as adult dosing by weight. Safe from 4 years.",
   "dosage_child_am":"ከ4 ዓመት ጀምሮ ደህንነቱ የተጠበቀ ነው።",
   "side_effects_en":"Nausea, abdominal pain, dizziness, headache. Usually mild and transient.",
   "contraindications_en":"Ocular cysticercosis (eye involvement). Pregnancy (first trimester — use with caution).",
   "warnings_en":"Take with food. Repeat dose after 6 weeks if symptoms persist."},

  {"id":"vitamin_a","name_en":"Vitamin A Supplement","name_am":"ቫይታሚን ኤ","generic_name":"retinol","category":"nutritional_supplement","aliases":["retinol","vitamin a capsule"],"used_for_conditions":["malnutrition","measles"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":False,
   "description_en":"Vitamin A supplementation prevents blindness, reduces measles severity by 50%, and reduces child mortality. Given to all children 6-59 months every 6 months in Ethiopia. Critical for immune function and vision.",
   "description_am":"ቫይታሚን ኤ ዕይታ ማጣትን ይከላከላል፣ ኩፍኝ ሞትን 50% ይቀንሳል። ለ6-59 ወር ህጻናት በ6 ወር ልዩነት ይሰጣል።",
   "dosage_adult_en":"Night blindness in pregnancy: 10,000 IU daily for 12 weeks. Postpartum: 200,000 IU single dose within 6 weeks of delivery.",
   "dosage_adult_am":"ለእርጉዝ ሴቶች: 10,000 IU በቀን ለ12 ሳምንት።",
   "dosage_child_en":"6-11 months: 100,000 IU every 6 months. 12-59 months: 200,000 IU every 6 months. Measles: 200,000 IU for 2 days.",
   "dosage_child_am":"6-11 ወር: 100,000 IU በ6 ወር ልዩነት። 12-59 ወር: 200,000 IU በ6 ወር ልዩነት።",
   "side_effects_en":"Safe at recommended doses. Overdose causes headache, nausea, bulging fontanelle in infants.",
   "contraindications_en":"Do not give high doses to pregnant women (teratogenic in first trimester).",
   "warnings_en":"Available free at all health posts in Ethiopia. Do not give high doses to pregnant women in first trimester."},
]

MEDS += [
  {"id":"azithromycin","name_en":"Azithromycin","name_am":"አዚትሮሚሲን","generic_name":"azithromycin","category":"antibiotic_macrolide","aliases":["zithromax","z-pak"],"used_for_conditions":["eye_infection","typhoid","cholera","upper_respiratory"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Azithromycin is a macrolide antibiotic used for trachoma (mass drug administration), typhoid, cholera, respiratory infections, and STIs. Single-dose treatment for trachoma makes it ideal for community programmes.",
   "description_am":"አዚትሮሚሲን ለትራኮማ፣ ታይፎይድ፣ ኮሌራ እና ሌሎች ኢንፌክሽኖች ጥቅም ላይ ይውላል።",
   "dosage_adult_en":"Trachoma: 1g single dose. Typhoid: 500mg daily for 7 days. Cholera: 1g single dose. Respiratory: 500mg day 1, then 250mg days 2-5.",
   "dosage_adult_am":"ትራኮማ: 1 ግራም አንድ ጊዜ። ታይፎይድ: 500 ሚሊ ግራም በቀን ለ7 ቀናት።",
   "dosage_child_en":"Trachoma: 20mg/kg single dose (max 1g). Respiratory: 10mg/kg day 1, then 5mg/kg days 2-5.",
   "dosage_child_am":"ትራኮማ: 20 ሚሊ ግራም/ኪሎ ግራም አንድ ጊዜ።",
   "side_effects_en":"Nausea, diarrhea, abdominal pain. Rare: cardiac arrhythmia (QT prolongation).",
   "contraindications_en":"Macrolide allergy. Liver disease. Caution with drugs that prolong QT interval.",
   "warnings_en":"Can be taken with or without food. Single dose for trachoma makes compliance easy."},

  {"id":"diazepam","name_en":"Diazepam","name_am":"ዲያዜፓም","generic_name":"diazepam","category":"benzodiazepine_anticonvulsant","aliases":["valium","stesolid"],"used_for_conditions":["epilepsy","tetanus"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Diazepam is used for acute seizure management (status epilepticus), tetanus muscle spasms, and anxiety. Rectal diazepam can be given by community health workers for prolonged seizures when IV access is unavailable.",
   "description_am":"ዲያዜፓም ለሽብርታ ህክምና እና ቴታነስ ጡንቻ ቁርጠት ጥቅም ላይ ይውላል።",
   "dosage_adult_en":"Status epilepticus: 10mg IV/rectal, repeat after 10 minutes if needed. Tetanus: 5-10mg IV every 1-8 hours.",
   "dosage_adult_am":"ሽብርታ: 10 ሚሊ ግራም IV/ሬክታል፣ አስፈላጊ ከሆነ ከ10 ደቂቃ በኋላ ይድገሙ።",
   "dosage_child_en":"0.3-0.5mg/kg IV/rectal. Max 10mg per dose. Rectal: 0.5mg/kg.",
   "dosage_child_am":"0.3-0.5 ሚሊ ግራም/ኪሎ ግራም IV/ሬክታል።",
   "side_effects_en":"Sedation, respiratory depression (especially IV), hypotension. Dependence with long-term use.",
   "contraindications_en":"Respiratory depression. Myasthenia gravis. Severe liver disease.",
   "warnings_en":"Have oxygen and resuscitation equipment ready when giving IV. Rectal route safe for community use."},

  {"id":"ceftriaxone","name_en":"Ceftriaxone","name_am":"ሴፍትሪያክሶን","generic_name":"ceftriaxone","category":"antibiotic_cephalosporin","aliases":["rocephin"],"used_for_conditions":["meningitis","pneumonia","typhoid","obstetric_emergency"],"available_in_ethiopia":True,"who_essential":True,"prescription_required":True,
   "description_en":"Ceftriaxone is a third-generation cephalosporin antibiotic given by injection. First-line for bacterial meningitis, severe pneumonia, typhoid, and neonatal sepsis. Once-daily dosing is convenient.",
   "description_am":"ሴፍትሪያክሶን ለባክቴሪያ ሜኒንጃይቲስ፣ ከባድ ሳምባ ምች እና ሌሎች ከባድ ኢንፌክሽኖች ጥቅም ላይ ይውላል።",
   "dosage_adult_en":"Meningitis: 2g IV/IM twice daily for 10-14 days. Pneumonia: 1-2g IV/IM once daily. Typhoid: 2g IV/IM once daily for 10-14 days.",
   "dosage_adult_am":"ሜኒንጃይቲስ: 2 ግራም IV/IM በቀን 2 ጊዜ ለ10-14 ቀናት።",
   "dosage_child_en":"50-100mg/kg/day IV/IM once daily. Meningitis: 100mg/kg/day. Neonatal sepsis: 50mg/kg once daily.",
   "dosage_child_am":"50-100 ሚሊ ግራም/ኪሎ ግራም/ቀን IV/IM።",
   "side_effects_en":"Pain at injection site, diarrhea, rash. Rare: biliary sludge with prolonged use.",
   "contraindications_en":"Cephalosporin or penicillin allergy. Do NOT mix with calcium-containing IV fluids in neonates.",
   "warnings_en":"Do not mix with calcium solutions. Reconstitute with lidocaine for IM injection to reduce pain."},
]

# ── Write back ────────────────────────────────────────────────────────────────
d['medications'] = MEDS
with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(d, f, ensure_ascii=False, indent=2)
print(f"Done. Added {len(MEDS)} medications to knowledge base.")
