# Generated by Django 4.2.7 on 2026-03-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='en', max_length=5)),
                ('symptoms', models.JSONField(default=list)),
                ('assessment_result', models.JSONField(blank=True, null=True)),
                ('urgency_level', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('woreda', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
