# Generated by Django 4.2.7 on 2026-04-15 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_accessibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('kebele', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HEWChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('newborn', 'Newborn Care'), ('sick_child', 'Sick Child'), ('postnatal', 'Postnatal'), ('antenatal', 'Antenatal'), ('family_planning', 'Family Planning'), ('nutrition', 'Nutrition')], max_length=30)),
                ('hew_name', models.CharField(blank=True, max_length=100)),
                ('kebele', models.CharField(blank=True, max_length=100)),
                ('household_id', models.CharField(blank=True, max_length=50)),
                ('visit_date', models.DateField()),
                ('checklist_data', models.JSONField(default=dict)),
                ('action_taken', models.TextField(blank=True)),
                ('referral_needed', models.BooleanField(default=False)),
                ('referral_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=50, unique=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('kebele', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('lmp_date', models.DateField()),
                ('edd', models.DateField(blank=True, null=True)),
                ('gravida', models.IntegerField(default=1)),
                ('parity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('delivered', 'Delivered'), ('closed', 'Closed')], default='active', max_length=20)),
                ('risk_factors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_id', models.CharField(max_length=50)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date_given', models.DateField()),
                ('dose_number', models.IntegerField(default=1)),
                ('facility', models.CharField(blank=True, max_length=200)),
                ('given_by', models.CharField(blank=True, max_length=100)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='api.child')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_measured', models.DateField()),
                ('age_months', models.FloatField()),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('muac_cm', models.FloatField(blank=True, null=True)),
                ('oedema', models.BooleanField(default=False)),
                ('nutrition_status', models.CharField(blank=True, max_length=30)),
                ('recorded_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='api.child')),
            ],
        ),
        migrations.CreateModel(
            name='ANCVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.IntegerField()),
                ('visit_date', models.DateField()),
                ('gestational_age_weeks', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('fundal_height_cm', models.FloatField(blank=True, null=True)),
                ('fetal_heart_rate', models.IntegerField(blank=True, null=True)),
                ('iron_folic_given', models.BooleanField(default=False)),
                ('tt_vaccine_given', models.BooleanField(default=False)),
                ('danger_signs', models.JSONField(default=list)),
                ('facility', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anc_visits', to='api.pregnancyrecord')),
            ],
        ),
    ]
