# Generated by Django 4.2.7 on 2026-04-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_phase3_sms_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kebele', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('vaccination_day', 'Vaccination Day'), ('chw_visit', 'CHW Visit'), ('anc_clinic', 'ANC Clinic'), ('health_education', 'Health Education Session'), ('other', 'Other')], max_length=30)),
                ('event_date', models.DateField(db_index=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_am', models.CharField(blank=True, max_length=200)),
                ('title_ti', models.CharField(blank=True, max_length=200)),
                ('title_om', models.CharField(blank=True, max_length=200)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=100)),
                ('condition_summary', models.TextField()),
                ('urgency_level', models.CharField(max_length=30)),
                ('contacts_notified', models.JSONField(default=list)),
                ('location_text', models.CharField(blank=True, max_length=200)),
                ('nearest_facility', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(max_length=50, unique=True)),
                ('patient_identifier', models.CharField(db_index=True, max_length=100)),
                ('patient_name', models.CharField(blank=True, max_length=100)),
                ('patient_phone', models.CharField(blank=True, max_length=20)),
                ('chw_identifier', models.CharField(db_index=True, max_length=100)),
                ('destination_facility', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('referral_date', models.DateField()),
                ('expected_visit_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('attended', 'Attended'), ('not_attended', 'Not Attended'), ('admitted', 'Admitted'), ('discharged', 'Discharged')], default='open', max_length=20)),
                ('outcome_notes', models.TextField(blank=True)),
                ('outcome_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('sms_reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraditionalRemedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedy_id', models.CharField(max_length=50, unique=True)),
                ('local_names', models.JSONField(default=dict)),
                ('common_use_en', models.TextField()),
                ('common_use_am', models.TextField(blank=True)),
                ('active_compounds', models.TextField(blank=True)),
                ('safety_notes_en', models.TextField(blank=True)),
                ('safety_notes_am', models.TextField(blank=True)),
                ('known_interactions', models.JSONField(default=list)),
                ('serious_adverse_effect', models.BooleanField(default=False)),
                ('evidence_level', models.CharField(blank=True, choices=[('documented', 'Documented'), ('traditional', 'Traditional'), ('unverified', 'Unverified')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='USSDSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hash', models.CharField(max_length=64, unique=True)),
                ('service_code', models.CharField(blank=True, max_length=20)),
                ('language_selected', models.CharField(blank=True, max_length=5)),
                ('symptom_selected', models.CharField(blank=True, max_length=50)),
                ('urgency_result', models.CharField(blank=True, max_length=30)),
                ('sms_sent', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('in_app', 'In-App')], default='sms', max_length=10)),
                ('remind_at', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendar_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='api.calendarevent')),
            ],
        ),
    ]
